server:
  port: 8091
spring:
  data:
    mongodb:
      host: 192.168.2.7
      port: 27017
      username: root
      password: example
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      value-deserializer:  edu.miu.swa.lab10.productquerryservice.KafkaCustomDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: INFO
    org:
      springfreamework: INFO

