server:
  port: 8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  application:
    name: productService

  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1