# configuration used from source https://medium.com/swlh/spring-cloud-high-availability-for-eureka-b5b7abcefb32
---
spring:
  profiles: default
server:
  port: 9000

eureka:
  server:
    renewal-percent-threshold: 0.85
  instance:
    hostname: default-eureka-server.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  config:
    activate:
      on-profile:
        - peer-1
  application:
    name: eureka-server-clustered
server:
  port: 9001
eureka:
  server:
    renewal-percent-threshold: 0.85
  instance:
    hostname: peer-1-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer-2-server.com:9002/eureka/,http://peer-3-server.com:9003/eureka/
---
spring:
  config:
    activate:
      on-profile:
        - peer-2
  application:
    name: eureka-server-clustered
server:
  port: 9002
eureka:
  server:
    renewal-percent-threshold: 0.85
  instance:
    hostname: peer-2-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer-1-server.com:9001/eureka/,http://peer-3-server.com:9003/eureka/

---
spring:
  config:
    activate:
      on-profile:
        - peer-3
  application:
    name: eureka-server-clustered
server:
  port: 9003
eureka:
  server:
    renewal-percent-threshold: 0.85
  instance:
    hostname: peer-3-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer-1-server.com:9001/eureka/,http://peer-2-server.com:9002/eureka/